<?php

return [
    'name' => 'Workflows',

    'default_reminder_channel' => 'IN_APP',

    'dependencies' => [
        'tasks'     => 'Tasks',
        'followups' => 'FollowUps',
        'reminders' => 'Reminders',
        'sms'       => 'Sms',
    ],

    'tokens' => [
        'appointment' => [
            'client_name' => 'نام بیمار',
            'client_phone' => 'شماره بیمار',
            'service_name' => 'نام خدمت',
            'provider_name' => 'نام پزشک',
            'appointment_date_jalali' => 'تاریخ نوبت (شمسی)',
            'appointment_time_jalali' => 'ساعت نوبت',
            'appointment_datetime_jalali' => 'تاریخ و ساعت نوبت',
            'payment_link' => 'لینک پرداخت',
        ],
        'statement' => [
            'statement_id' => 'شناسه صورت وضعیت',
            'provider_name' => 'نام پزشک',
            'provider_phone' => 'شماره پزشک',
            'start_date' => 'تاریخ شروع',
            'end_date' => 'تاریخ پایان',
            'status' => 'وضعیت',
            'first_appointment_time' => 'ساعت اولین نوبت',
            'last_appointment_time' => 'ساعت آخرین نوبت',
            'notes' => 'یادداشت',
        ],
        'client' => [
            'client_id' => 'شناسه بیمار/کلاینت',
            'client_name' => 'نام بیمار',
            'client_username' => 'نام کاربری',
            'client_phone' => 'شماره بیمار',
            'client_email' => 'ایمیل بیمار',
            'client_national_code' => 'کد ملی بیمار',
            'client_case_number' => 'شماره پرونده',
            'client_notes' => 'یادداشت پرونده',
            'client_status' => 'وضعیت پرونده',
            'client_created_at_jalali' => 'تاریخ ایجاد پرونده (شمسی)',
            'client_creator_name' => 'نام ثبت‌کننده پرونده',
        ],
        'call' => [
            'call_id' => 'شناسه تماس',
            'call_date' => 'تاریخ تماس',
            'call_time' => 'زمان تماس',
            'call_reason' => 'علت تماس',
            'call_result' => 'نتیجه تماس',
            'call_status' => 'وضعیت تماس',
            'call_direction' => 'جهت تماس',
            'call_duration' => 'مدت تماس (ثانیه)',
            'call_notes' => 'یادداشت‌های تماس',
            'call_next_action' => 'اقدام بعدی',
            'call_next_action_date' => 'تاریخ اقدام بعدی',
            'call_phone' => 'شماره تماس',
        ],
        'task' => [
            'task_id' => 'شناسه وظیفه',
            'task_title' => 'عنوان وظیفه',
            'task_description' => 'توضیحات وظیفه',
            'task_type' => 'نوع وظیفه',
            'task_status' => 'وضعیت وظیفه',
            'task_priority' => 'اولویت وظیفه',
            'task_due_at' => 'مهلت انجام',
            'task_completed_at' => 'زمان تکمیل',
            'task_assignee_name' => 'نام مسئول انجام',
            'task_assignee_phone' => 'شماره مسئول انجام',
            'task_creator_name' => 'نام ایجادکننده وظیفه',
        ],
        'followup' => [
            'followup_id' => 'شناسه پیگیری',
            'followup_title' => 'عنوان پیگیری',
            'followup_description' => 'توضیحات پیگیری',
            'followup_status' => 'وضعیت پیگیری',
            'followup_priority' => 'اولویت پیگیری',
            'followup_due_at' => 'مهلت پیگیری',
            'followup_completed_at' => 'زمان تکمیل پیگیری',
            'followup_assignee_name' => 'نام مسئول پیگیری',
            'followup_assignee_phone' => 'شماره مسئول پیگیری',
            'followup_creator_name' => 'نام ایجادکننده پیگیری',
        ],
    ],
];
